---

- name: Install dependences
  yum: name={{ item }} state=present
  with_items:
      - rhevm
      - glusterfs-fuse
      - python-enum34
  tags:
    - packages

- name: Stop and disable NetworkManager
  service:
      name: NetworkManager
      enabled: no
      state: stopped
  tags:
    - setup

- name: create qci directory
  file:
      path: /etc/qci
      state: directory
      mode: 0700
  tags:
    - setup

- name: Get the answer file over there
  template:
      src: answers.j2
      dest: /etc/qci/answers
      mode: 0600
  tags:
    - setup

- name: check if the setup has already run
  command: systemctl status ovirt-engine
  register: installed
  changed_when: false
  ignore_errors: yes

- name: Execute engine setup
  shell: |
    engine-setup --offline --config-append=/etc/qci/answers
  async: 12000
  poll: 30
  when: installed|failed
  tags:
    - install
