---

- hosts: engine
  remote_user: root
  roles:
    - override_tty
    - engine
    - { role: wait_for_rhevm, tags: ['config'] }
    - datacenter

- hosts: hypervisor
  remote_user: root
  roles:
    - override_tty
    - hypervisor
    - { role: register_hypervisor, script_runner: '{{ engine_fqdn }}' }

- hosts: engine
  remote_user: root
  roles:
    - storage
