---

- hosts: self_hosted_first_host
  remote_user: root
  roles:
    - override_tty
    - { role: subscription, when: '{{ repositories|length > 0 }}'}
    - self_hosted_first_host
    - { role: wait_for_engine, tags: ['config'] }
    - datacenter
    - storage

- hosts: self_hosted_additional_hosts
  remote_user: root
  roles:
    - override_tty
    - { role: subscription, when: '{{ repositories|length > 0 }}'}
    - self_hosted_additional_host
