---

- name: Install dependences (~2GB)
  yum: name={{ item }} state=present
  with_items:
      - genisoimage
      - rhevm-appliance
      - glusterfs-fuse
      - ovirt-hosted-engine-setup
  tags:
    - packages

- name: Stop and disable NetworkManager
  service:
      name: NetworkManager
      enabled: no
      state: stopped
  tags:
    - setup

- name: Create qemu group
  group:
      name: qemu
      state: present
      system: yes
  tags:
    - setup

- name: Create qemu user
  user:
      name: qemu
      group: qemu
      createhome: no
      system: yes
  tags:
    - setup


- name: Find the path to the appliance image
  shell: find /usr/share/ovirt-engine-appliance -name 'rhevm-appliance-*.ova'
  register: rhevm_appliance
  tags:
    - setup

- name: get the provisioning nic for the machine
  shell: |
    ip addr | grep -Pzo '^[0-9]+:(.*):.*\n.*{{ mac_address }}.*' | sed -r -n 's/[0-9]+: (.*):.*/\1/p' | head -n1
  register: provisioning_interface
  tags:
    - setup

- name: print appliance path
  debug: msg={{rhevm_appliance}}
- name: print provisioning nic
  debug: msg={{provisioning_interface}}



- name: create qci directory
  file:
      path: /etc/qci
      state: directory
      mode: 0700
      owner: qemu
      group: qemu
  tags:
    - setup

- name: Get the answer file over there
  template:
      src: answers.j2
      dest: /etc/qci/answers
      mode: 0600
  tags:
    - setup

- name: Create cloud init temp directory
  file:
      path: '/etc/qci/cloud_init'
      state: directory
      mode: 0700
      owner: qemu
      group: qemu
  tags:
    - setup

- name: Copy over the cloud init data
  template:
      src: '{{ item.src }}'
      dest: '{{ item.dest }}'
      owner: qemu
      group: qemu
      mode: 0600
  with_items:
    - { src: user-data.j2, dest: /etc/qci/cloud_init/user-data }
    - { src: meta-data.j2, dest: /etc/qci/cloud_init/meta-data }
  tags:
    - setup

- name: Generate cloud-init iso
  shell: |
    genisoimage -output '/etc/qci/cloud_init/cloud.iso' -volid cidata -joliet -rock -input-charset utf-8  '/etc/qci/cloud_init/meta-data' '/etc/qci/cloud_init/user-data'
  tags:
    - setup

- name: Fix permissions on iso
  file:
      name: /etc/qci/cloud_init/cloud.iso
      group: qemu
      owner: qemu
      state: file
      mode: 0600
  tags:
    - setup

- name: Execute hosted-engine setup
  shell: |
    hosted-engine --deploy --config-append=/etc/qci/answers
  async: 12000
  poll: 30
  tags:
    - install
