---

timeout: 300
private_key_path: '{{ ansible_ssh_private_key_file if ansible_ssh_private_key_file is defined else False }}'
extra_ssh_args:  -o PasswordAuthentication=no -o StrictHostKeyChecking=no
